config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # Language wrapper
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    # "/en" OR "/ar"
    get "/", to: "user/pages#home", as: "home"
    
    # User Routes "/user"
    get "pages", to: "user/pages#home"
    get "pages/home", to: "user/pages#home"

    # Set user session
    get "/set_user", to: "user/pages#set_user", as: "set_user"

    # Add to cart
    # POST "/add_to_cart/:id"
    post "add_to_cart", to: "user/pages#add_to_cart", as: "add_to_cart"
    # Remove from cart
    # POST "/remove_from_cart/:id"
    post "remove_from_cart", to: "user/pages#remove_from_cart", as: "remove_from_cart"
    # Increment quantity
    # POST "/increment_quantity/:id"
    post "increment_quantity", to: "user/pages#increment_quantity", as: "increment_quantity"
    # decrement quantity
    # POST "/decrement_quantity/:id"
    post "decrement_quantity", to: "user/pages#decrement_quantity", as: "decrement_quantity"
    # Checkout (generate bill)
    # POST "/checkout"
    post "checkout", to: "user/pages#checkout", as: "checkout"

    get "generate_invoice",  to: "user/pages#generate_invoice", as: "generate_invoice"


    # Admin Routes "/admin"
    namespace :admin do
      # Market routes 
      # GET "/markets", GET "/markets/:id"
      # PUT "/markets/:id", POST "/markets", DELETE "/markets/:id"
      resources :markets

      # GET "/categories", GET "/categories/:id"
      # PUT "/categories/:id", POST "/categories", DELETE "/categories/:id"
      resources :categories

      # Upload product routes
      # GET "/products/new_upload"
      get "products/new_upload", to: "products#new_upload", as: "new_upload"
      # POST "/products/new_upload"
      post "products/upload_products", to: "products#upload_products", as: "upload_products"
      # GET "/products", GET "/products/:id"
      # PUT "/products/:id", POST "/products", DELETE "/products/:id"
      resources :products

      # Orders Routes
      # GET "/orders"
      get "orders", to: "orders#index", as: "orders"
      # GET "/order/:id"
      get "order/:id", to: "orders#show", as: "order"
      # DELETE "order/:id"
      delete "order/:id", to: "orders#destroy", as: "destroy_order"
      # GET "/invoice/:id"
      get "invoice/:id", to: "orders#view_invoice", as: "invoice"
      # POST "/generate_invoice/:order_id"
      post "invoice/:id", to: "orders#generate_invoice", as: "generate_invoice"

      # Users Routes
      # GET "/users"
      resources :users, only: [:index, :show, :edit, :update]

      # Settings Routes
      # GET "/settings"
      get "settings", to: "settings#index", as: "settings"
      # POST "/change_settings"
      post "change_settings", to: "settings#change_settings", as: "change_settings"
      
      # Admin Landing page "/admin"
      get "/", to: "pages#main"
      get "pages/main"
      # No route match
      # TODO: create a route for undefined routes for admins
    end

    # No routes match
    get "*path", to: "user/pages#no_match", as: "no_match"
  end
  
  # Root "/"
  root "user/pages#home"
  get "*path", to: redirect("/#{I18n.locale}/%{path}")
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id           :bigint           not null, primary key
#  name         :string
#  mobile       :string
#  email        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  visits_count :integer          default(1)
#  last_visit   :datetime
#
require 'uri'
class User < ApplicationRecord
    has_many :orders, dependent: :destroy
    # validates :mobile, presence: true , format: { with: /\A[0-9]{9}\z/, on: :create }
    # validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" }

    default_scope { includes(:orders) }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users = @users.page params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :mobile, :email)
    end
end

app/controllers/user/pages_controller.rb
class User::PagesController < UserController
  # before_action :set_cart
  require "wicked_pdf"
  # Main landing page
  def home
    # raise ''
    @categories = Category.all.order("name#{or_en}").includes('products')
    # @top_products = Product.all.sample(10)
    # raise ''


    category_filter = params[:category]
    @search_term = params[:term]

    # Filter products with category or search term
    @products = Product.all
    @products = @products.where(category_id: category_filter) if category_filter
    @products = @products.where("name#{or_en} ILIKE ?", "%#{@search_term}%") if @search_term

    @products = @products.order("name#{or_en}").page params[:page]
    @products_count = @cart.order_products.size
  end

  # Add to cart action
  def add_to_cart
    @current_product = @cart.order_products.find_by(product_id: params[:order_product][:product_id])
    if @current_product
      @current_product.quantity += params[:order_product][:quantity].to_i
      @current_product.save
    else
      @current_product = @cart.order_products.create(product_params)
    end
    @products_count = @cart.order_products.size

    respond_to do |format|
      format.js
    end
  end
  
  # Remove from cart action
  def remove_from_cart
    @current_product = @cart.order_products.find(params[:id])
    @current_product.destroy
    @products_count = @cart.order_products.count
    
    respond_to do |format|
      format.js
    end
  end

  def increment_quantity
    @item = @cart.order_products.find(params[:item_id])
    @item.quantity += 1
    @item.save

    respond_to do |format|
      format.js
    end
  end
  
  def decrement_quantity
    @item = @cart.order_products.find(params[:item_id])
    @item.quantity -= 1 if @item.quantity > 1
    @item.save

    respond_to do |format|
      format.js
    end
  end

  def checkout
    # Get params
    name = params[:user_name]
    # phone = params[:user_phone]
    # email = params[:user_email]

    # # Remove 0 or +966 from phone number
    # phone = phone[1..phone.length] if phone.starts_with? "0"
    # phone = phone[4..phone.length] if phone.starts_with? "+"

    # Successful message
    msg = { notice: t("messages.checkedout") }
    validated = true

    # Validate Phone and email
    # if !User.find_or_create_by(mobile: phone).valid?
    #   msg = { alert: t("errors.invalid_phone") }
    #   validated = false
    # end

    # Validate Order
    if @cart.order_products.size == 0
      msg = { alert: t("errors.empty_cart") }
      validated = false
    end

    # Update  user if exists, or create one
    if validated
      user = User.find_or_create_by(id: session[:user_id])
      #user = User.find_or_create_by(mobile: phone)
      #user.email = email
      user.name = name if !name.empty?
      user.save
      # Attach order to user
      @cart.user_id = user.id
      @cart.checkout_at = DateTime.now
      @cart.save
      # Clear cart session
      session.delete(:cart_id)
      if @cart.save == true

        redirect_to controller: 'pages', action: 'generate_invoice', id: @cart.id , format: :pdf and return
      end  
    end
    redirect_to home_path, flash: msg
  end



  def generate_invoice

    @order   = Order.find(params[:id])
    @order_products = @order.order_products
    @markets = Market.active
    @counts = {
            product_count: @order_products.size,
            quantity_count: @order_products.sum { |item| item.quantity }
        }

      respond_to do  |format|
        format.pdf { 
          render template: 'user/pages/view_invoice',
          pdf: 'invoice',
          dpi: 1000,
          layout: 'pdf.html',
          encoding:"UTF-8", 
          disposition: 'attachment'}
        format.html
      end 
  end   

  def set_user
    if(session[:user_id] && !session[:user_id].empty?)
      @user = User.find(session[:user_id])
    elsif(params[:user_id] && !params[:user_id].empty?)
      @user = User.find_or_create_by(id: params[:user_id])
    else
      @user = User.create
    end
    if(((Time.now - @user.last_visit) / 1.hour).round(4) >= @visit_timer)
      @user.increment!(:visits_count, 1)
      @user.update(last_visit: DateTime.now)
    end
    session[:user_id] = @user.id

    respond_to do |format|
      format.json { render json: @user.id }
    end
  end

  # Case of unmatched route 
  def no_match
    redirect_to({ action: "home" }, flash: { alert: t("errors.routes.no_match") })
  end


  private

  def product_params
    params.require(:order_product).permit(:quantity, :product_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    protect_from_forgery
    before_action :clear_empty_carts
    before_action :set_cart


    protected
    
    private

    def clear_empty_carts
        Order.empty_carts.destroy_all
    end

    def set_cart
        @cart = Order.find(session[:cart_id])
        rescue ActiveRecord::RecordNotFound
        @cart = Order.create
        session[:cart_id] = @cart.id
    end
end

app/helpers/user/pages_helper.rb
module User::PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/pages/_filter.pdf.erb
<div class="accordion mb-5" id="accordionExample">
    <div class="card">
        <div class="card-header pointer" id="headingOne" data-toggle="collapse" data-target="#filter" aria-expanded="true" aria-controls="filter">
            <h5 class="mb-0">
                <%= t ".filter" %>
            </h5>
        </div>
        <div id="filter" class="collapse <%= 'show' if params[:filtering] %>" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                <%= form_with model: @filter, url_fo: admin_orders_path, local: true, method: :get, id: 'filter-form' do |f| %>
                    <%= f.hidden_field :filtering %>
                    <div class="fomr-group row my-3">
                        <div class="col-md-6 row">
                            <%= f.label t(".customer_phone"), for: "customer_phone", class: 'col-md-4' %>
                            <%= f.text_field :customer_phone, class: 'form-control col-md-8', value: params[:product_name] ? params[:product_name] : '' %>
                        </div>
                    </div>
                    <div class="fomr-group row my-3">
                        <div class="col-md-6 row">
                            <%= f.label t(".confirmation"), class: 'col-md-4', for: 'confirmation' %>
                            <%= f.select :confirmation, options_for_select([[t(".all"), 0], [t(".is_confirmed"), 1], [t(".not_confirmed"), 2]], params[:confirmation]), {}, {class: 'form-control', :style => 'width: 200px'} %>
                        </div>
                    </div>
                    <div class="form-group mt-5 text-center">
                        <%= f.submit t(".submit"), class: 'btn btn-outline-info' %>
                        <div class="gap-x-sm"></div>
                        <%= link_to t(".clear"), admin_orders_path, class: 'btn btn-outline-danger' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/user/pages/_order_details.pdf.erb
<div class="row">
    <div class="col">
        <h5><%= t ".order_products" %></h5>
        <br>
        <table class="table table-hover text-center">
            <thead class="thead-light">
                <th>#</th>
                <th><%= t ".image" %></th>
                <th><%= Product.human_attribute_name("name#{is_ar ? '' : '_en'}") %></th>
                <th><%= t ".quantity" %></th>
            </thead>
            <tbody>
                <% if @order_products.size == 0 %>
                    <tr>
                        <td colspan="4" class="text-danger">
                            <%= t ".no_products" %>
                        </td>
                    </tr>
                <% end %>
                <% @order_products.each_with_index do |item, i| %>
                    <% product = item.product %>
                        <tr>
                            <td>
                                <%= i + 1 %>
                            </td>
                            <td>
                                <%= image_tag product.main_image, class: 'product-image' if product.main_image && !product.main_image.empty? %>
                            </td>
                            <td>
                                <%= link_to product.lang_name, admin_product_path(product) %>
                            </td>
                            <td>
                                <p><%= item.quantity %></p>
                            </td>
                        </tr>
                <% end %>
            </tbody>
            <tfoot class="tfoot-dark">
                <tr>
                    <td>
                        <%= t ".total_products" %>
                    </td>
                    <td>
                        <%= @counts[:product_count] %>
                    </td>
                    <td>
                        <%= t ".total_quantity" %>
                    </td>
                    <td>
                        <%= @counts[:quantity_count] %>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="gap-x-sm"></div>
    <div class="col">
        <h5><%= t ".order_times" %></h5>
        <br>
        <ul class="list-group list-group-flush">
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".id"%>:</strong>
                <div class="gap-x-sm"></div>
                <span class="text-center">
                    <%= @order.id %>
                </span>
            </li>
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".created_at"%>:</strong>
                <div class="gap-x-sm"></div>
                <span class="text-center">
                    <%= format_date @order.created_at %>
                </span>
            </li>
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".ordered_at"%>:</strong>
                <div class="gap-x-sm"></div>
                <span class="text-center">
                    <%= format_date @order.checkout_at if @order.checkout_at %>
                </span>
            </li>
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".confirmed_at"%>:</strong>
                <div class="gap-x-sm"></div>
                <% if @order.confirmed %>
                    <span class="text-center text-success">
                        <%= format_date(@order.created_at) %>
                    </span>
                <% else %>
                    <span class="text-center text-danger">
                        <%= t(".not_confirmed") %>
                    </span>
                <% end %>
            </li>
            <% if @order.admin %>
                <li class="list-group-item list-group-item-action d-flex">
                    <strong style="min-width: 200px;"><%= t ".confirmed_by"%>:</strong>
                    <div class="gap-x-sm"></div>
                    <span class="text-center text-info">
                        <%= @order.admin.email %>
                    </span>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/user/pages/_prices_details.pdf.erb
<%
    totals = {}
    total_quantity = 0
%>
<div>
    <table class="table table-hover text-center">
        <thead>
            <th class="bg-light"><%= Product.model_name.human %></th>
            <th><%= t ".quantity" %></th>
            <% @markets.each do |market| %>
                <th>
                    <%= market.lang_name %>
                </th>
            <% end %>
        </thead>
        <tbody>
            <% if @order_products.size == 0 %>
                <tr>
                    <td colspan="4" class="text-danger">
                        <%= t ".no_products" %>
                    </td>
                </tr>
            <% end %>
            <% @order_products.each do |item| %>
                <% product = item.product %>
                <% quantity = item.quantity %>
                <tr>
                    <td class="bg-light" style="max-width: 150px">
                        <%= product.lang_name %>
                    </td>
                    <td>
                        <% total_quantity += quantity %>
                        <%= quantity %>
                    </td>
                    <% product.informations.order_by_market_name.each do |item_price| %>
                        <td>
                            <% price = item_price.price.to_f * quantity %>
                            <% totals[item_price.market_id] = totals[item_price.market_id] ? totals[item_price.market_id] + price : price %>
                            <%= number_to_currency price, locale: @lang %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
        <tfoot class="tfoot-dark">
            <tr>
                <td><%= t ".total" %></td>

                <td><%= totals['quantity'] %></td>
                
                <%
                    min = totals.min_by{ |k,v| v }
                    max = totals.max_by{ |k,v| v }
                %>

                <% @markets.each do |market| %>
                    <% if min.last && totals[market.id] == min.last %>
                        <td class="text-success">
                            <%= number_to_currency totals[market.id], locale: @lang %>
                        </td>
                    <% elsif max.last && totals[market.id] == max.last %>
                        <td class="text-danger">
                            <%= number_to_currency totals[market.id], locale: @lang %>
                        </td>
                    <% else %>
                        <td>
                            <%= number_to_currency totals[market.id], locale: @lang %>
                        </td>
                    <% end %>
                <% end %>
            </tr>
        </tfoot>
    </table>
    <br><br>
    <div class="row third-width">
        <% text_align = is_ar ? 'right' : 'left' %>
        <div class="col-md-5 text-<%= text_align %>">
            <strong><%= t ".saving_amount" %>:</strong>
        </div>
        <div class="col text-success text-<%= text_align %>">
            <%= number_to_currency (max.last - min.last).round(2), locale: @lang %>
        </div>
    </div>
</div>

app/views/user/pages/_products.html.erb
<% @products.each do |product| %>
    <% id = product.id%>
    <div class="card card-item mb-5 mx-auto">
        <div class="d-flex justify-content-center align-items-center" style="height: 100%;">
            <%= image_tag product.main_image, class: 'card-img-top' if product.main_image && !product.main_image.empty? %>
        </div>
        <%= form_with model: OrderProduct, url: add_to_cart_path do |f| %>
            <div class="card-body d-flex flex-column justify-content-end">
                    <h5 class="card-title"><%= product.lang_name %></h5>
                    <div class="divider"></div>
                    <%# <p class="card-text">Description ...</p> %>
                    <div class="text-center row mb-3 mx-auto">
                        <div class="col row p-2 text-center mx-auto">
                                <span
                                    id="increment-btn-<%= id %>"
                                    class="pointer success btn btn-no-highlight col-xs-4 increment-btn"
                                    style="font-weight: bold">+</span>

                                <%= f.number_field :quantity, min: 1, value: 1, class: 'form-control text-center col-md-4 m-auto', id: "input-#{id}" %>

                                <%= f.hidden_field :product_id, value: id %>
                                
                                <span
                                    id="decrement-btn-<%= id %>"
                                    class="pointer success btn btn-no-highlight col-xs-4 decrement-btn"
                                    style="font-weight: bold">-</span>
                        </div>
                    </div>
                    <% if @show_lowest_price && product.lowest_price %>
                        <div class="row pt-1">
                            <p class="text-center full-width">
                                <%= t ".unit_price" %>
                                <b>
                                    <%= number_to_currency(product.lowest_price, locale: @lang) %>
                                </b>
                            </p>
                        </div>
                    <% end %>
                    <% if @show_saving_percentage && product.lowest_price && product.highest_price && product.highest_price > 0 %>
                        <div class="row">
                            <p class="text-center full-width text-success">
                                <%= t ".saving_percent" %>
                                <%= number_to_percentage((((product.highest_price - product.lowest_price) / product.highest_price) * 100), precision: 0) %>
                            </p>
                        </div>
                    <% end %>
            </div>
            <div class="card-footer">
                <div class="text-center row">
                    <div class="col align-items-center">
                        <%= f.submit t('.add_to_cart'), class: 'btn btn-outline-success text-center col-md-8 pt-3 add-to-cart' %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

<script>
    $('.add-to-cart').click(function(e){
        var msg = "<%= is_ar ? 'تمت الإضافة للسلة' : 'Item Added To Cart' %>";
        Swal.fire({
            type: 'success',
            title: `${msg}`,
            showConfirmButton: false,
            timer: 800
        });
    });
</script>

app/views/user/pages/_user_details.pdf.erb
<% user = @order.user %>
<div class="row mb-5 pb-5">
    <ul class="list-group list-group-flush col-md-4">
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".id"%>:</strong>
            <span class="text-center">
                <%= user.id %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".name"%>:</strong>
            <span class="text-center">
                <%= link_to user.name, admin_user_path(user) %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".phone"%>:</strong>
            <span class="text-center">
                <%= user.mobile %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".email"%>:</strong>
            <span class="text-center">
                <%= user.email != '' ? user.email : t(".no_email") %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".order_count"%>:</strong>
            <span class="text-center">
                <%= user.orders.size %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".joined_at"%>:</strong>
            <span class="text-center">
                <%= format_date user.created_at %>
            </span>
        </li>
    </ul>
</div>

app/views/user/pages/add_to_cart.js.erb
$(".cart_list").html(`<%= render 'user/pages/cart/list', cart_items: @cart.order_products %>`);
$("#cart_badge").html('<%= render 'user/pages/cart/cart_badge', count: @products_count %>');
$("#empty_cart").remove();

app/views/user/pages/decrement_quantity.js.erb
$("#cart-quantity-<%= @item.id %>").val(<%= @item.quantity %>);

app/views/user/pages/home.html.erb
<div class="my-5">
    <div class="text-center mb-5">
        <%= link_to image_tag('user/price_tag.jpg', style:'width:830px; hight:120px;', class:"img-fluid") %>
    </div>
    <%= form_with id: 'filter-form', url: home_path, method: :get, local: true, class: "text-center" do |f| %>
        <% unless @categories.length == 0 %>

            <div class="d-inline-block">
                <%= link_to t('.all'), '/', class: 'text-info category-display' %>
            </div>
            <div class="gap-x-sm"></div>
            <% @categories.each do |category| %>
                <% if category.products.length > 0 %>
                    <% id = category.id %>
                    <div class="d-inline-block">
                        <%= f.label category.lang_name, for: "category_#{id}", id: "category-#{id}", class: 'category-display text-info pointer a-category' %><br />
                        <% check = params[:category].to_i == id ? true : false %>
                        <%= f.radio_button :category, id, class: 'd-none', checked: check %>
                    </div>
                    <div class="gap-x-sm"></div>
                <% end %>
            <% end %>
        <% end %>
        <div>
        
        <div class="form-group my-5">
            <%= f.text_field :term, class: 'form-control two-thirds-width mx-auto', placeholder: t(".search"), value: @search_term %>
        </div>
    <% end %>
    <h3 class="font-weight-bold my-3 py-3 text-<%= is_ar ? 'right' : 'left' %>">توفير اكثر</h3>
    <div class="divider"></div>
    <h3 class="font-weight-bold my-3 py-3 text-<%= is_ar ? 'right' : 'left' %>">الاكثرا طلبا</h3>
    <div class="divider"></div>
    <h3 class="font-weight-bold my-3 py-3 text-<%= is_ar ? 'right' : 'left' %>">المنتجات</h3>
    <div class="divider"></div>
    
</div>
<div class="row my-3 mx-auto">
    <% if @products.length == 0 %>
        <p class="m-auto text-center text-secondary"><%= t ".no_items" %></p>
    <% end %>
    <%= render partial: 'products' %>
</div>
<div class="row my-2 mx-auto pagination">
    <%= paginate @products, window: 2 %>
</div>

<script>

    /* Decrement quantity of a product (unless it's equal 1) */
    jQuery(document).ready( function($) {

        $.ajax({
            type: 'GET',
            url: "<%= set_user_path %>",
            data: {
                user_id: localStorage.getItem('user_id')
            },
            dataType: 'json',
            success: function(user_id){
                localStorage.setItem('user_id', user_id)
                console.log(user_id);
            }
        });

        $('.a-category').click(function(e){
            var category_id = e.target.id.split('-')[1];
            var radio = $(`#category_${category_id}`);
            
            radio.attr('checked', 'checked');
            $('#filter-form').submit();
        });
        
        $('.decrement-btn').click(function(){
            var id = $(this).attr('id').split('-');
            id = id[id.length-1];
            $(`#input-${id}`).val(function(i, value){
                if(value > parseInt($(this).attr('min')))
                    return --value;
                return value;
            });
        });

        /* Increment quantity of a product */
        $('.increment-btn').click(function(){
            var id = $(this).attr('id').split('-');
            id = id[id.length-1];
            $(`#input-${id}`).val(function(i, value){
                return ++value;
            });
        });
    });
</script>

app/views/user/pages/increment_quantity.js.erb
$("#cart-quantity-<%= @item.id %>").val(<%= @item.quantity %>);

app/views/user/pages/remove_from_cart.js.erb
$("#cart_item_<%= @current_product.id %>").remove();
$("#cart_badge").html('<%= render 'user/pages/cart/cart_badge', count: @products_count %>');
<% if @products_count == 0 %>
    $('#cart_list').append(`<%= render partial: 'user/pages/cart/empty_cart' %>`);
<% end %>