config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # Language wrapper
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    # "/en" OR "/ar"
    get "/", to: "user/pages#home", as: "home"
    
    # User Routes "/user"
    get "pages", to: "user/pages#home"
    get "pages/home", to: "user/pages#home"

    # Set user session
    get "/set_user", to: "user/pages#set_user", as: "set_user"

    # Add to cart
    # POST "/add_to_cart/:id"
    post "add_to_cart", to: "user/pages#add_to_cart", as: "add_to_cart"
    # Remove from cart
    # POST "/remove_from_cart/:id"
    post "remove_from_cart", to: "user/pages#remove_from_cart", as: "remove_from_cart"
    # Increment quantity
    # POST "/increment_quantity/:id"
    post "increment_quantity", to: "user/pages#increment_quantity", as: "increment_quantity"
    # decrement quantity
    # POST "/decrement_quantity/:id"
    post "decrement_quantity", to: "user/pages#decrement_quantity", as: "decrement_quantity"
    # Checkout (generate bill)
    # POST "/checkout"
    post "checkout", to: "user/pages#checkout", as: "checkout"

    get "generate_invoice",  to: "user/pages#generate_invoice", as: "generate_invoice"


    # Admin Routes "/admin"
    namespace :admin do
      # Market routes 
      # GET "/markets", GET "/markets/:id"
      # PUT "/markets/:id", POST "/markets", DELETE "/markets/:id"
      resources :markets

      # GET "/categories", GET "/categories/:id"
      # PUT "/categories/:id", POST "/categories", DELETE "/categories/:id"
      resources :categories

      # Upload product routes
      # GET "/products/new_upload"
      get "products/new_upload", to: "products#new_upload", as: "new_upload"
      # POST "/products/new_upload"
      post "products/upload_products", to: "products#upload_products", as: "upload_products"
      # GET "/products", GET "/products/:id"
      # PUT "/products/:id", POST "/products", DELETE "/products/:id"
      resources :products

      # Orders Routes
      # GET "/orders"
      get "orders", to: "orders#index", as: "orders"
      # GET "/order/:id"
      get "order/:id", to: "orders#show", as: "order"
      # DELETE "order/:id"
      delete "order/:id", to: "orders#destroy", as: "destroy_order"
      # GET "/invoice/:id"
      get "invoice/:id", to: "orders#view_invoice", as: "invoice"
      # POST "/generate_invoice/:order_id"
      post "invoice/:id", to: "orders#generate_invoice", as: "generate_invoice"

      # Users Routes
      # GET "/users"
      resources :users, only: [:index, :show, :edit, :update]

      # Settings Routes
      # GET "/settings"
      get "settings", to: "settings#index", as: "settings"
      # POST "/change_settings"
      post "change_settings", to: "settings#change_settings", as: "change_settings"
      
      # Admin Landing page "/admin"
      get "/", to: "pages#main"
      get "pages/main"
      # No route match
      # TODO: create a route for undefined routes for admins
    end

    # No routes match
    get "*path", to: "user/pages#no_match", as: "no_match"
  end
  
  # Root "/"
  root "user/pages#home"
  get "*path", to: redirect("/#{I18n.locale}/%{path}")
end

app/views/layouts/partials/admin/navigation/items/_category.html.erb
<li class="<%= 'active' if @current_path.include?('categories') %>">
    <a href="#categorySubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <%= t ".categories" %>
    </a>
    <ul class="collapse list-unstyled <%= 'show' if @current_path.include?('categories') %>" id="categorySubmenu">
        <li>
            <% active_class = @current_path.last == 'categories' ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.view_categories'), admin_categories_path, class: active_class %>
        </li>
        <li>
            <% active_class = @current_path.include?('new') && @current_path.include?('categories') ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.new_category'), new_admin_category_path, class: active_class %>
        </li>
    </ul>
</li>

app/views/layouts/partials/admin/navigation/items/_market.html.erb
<li class="<%= 'active' if @current_path.include?('markets') %>">
    <a href="#marketSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle in">
        <%= t ".markets" %>
    </a>
    <ul class="collapse list-unstyled <%= 'show' if @current_path.include?('markets') %>" id="marketSubmenu">
        <li>
            <% active_class = @current_path.last == 'markets' ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.view_markets'), admin_markets_path, class: active_class %>
        </li>
        <li>
            <% active_class = @current_path.include?('new') && @current_path.include?('markets') ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.new_market'), new_admin_market_path, class: active_class %>
        </li>
    </ul>
</li>

app/views/layouts/partials/admin/navigation/items/_order.html.erb
<li class="<%= 'active' if @current_path.include?('orders') %>">
    <a href="#orderSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <%= t ".orders" %>
    </a>
    <ul class="collapse list-unstyled <%= 'show' if @current_path.include?('orders') ||  @current_path.include?('invoice') %>" id="orderSubmenu">
        <li>
            <% active_class = @current_path.last == 'orders' ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.view_orders'), admin_orders_path, class: active_class %>
        </li>
    </ul>
</li>

app/views/layouts/partials/admin/navigation/items/_product.html.erb
<li class="<%= 'active' if @current_path.include?('products') %>">
    <a href="#productSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <%= t ".products" %>
    </a>
    <ul class="collapse list-unstyled <%= 'show' if @current_path.include?('products') %>" id="productSubmenu">
        <li>
            <% active_class = @current_path.last == 'products' ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.view_products'), admin_products_path, class: active_class %>
        </li>
        <li>
            <% active_class = @current_path.include?('new') && @current_path.include?('products') ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.new_product'), new_admin_product_path, class: active_class %>
        </li>
        <li>
            <% active_class = @current_path.include?('new_upload') && @current_path.include?('products') ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.upload_products'), admin_new_upload_path, class: active_class %>
        </li>
    </ul>
</li>

app/views/layouts/partials/admin/navigation/items/_settings.html.erb
<li class="<%= 'active' if @current_path.last == 'settings' %>">
    <%= link_to t('.settings'), admin_settings_path %>
</li>

app/views/layouts/partials/admin/navigation/items/_users.html.erb
<li class="<%= 'active' if @current_path.include?('users') %>">
    <a href="#userSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <%= t ".users" %>
    </a>
    <ul class="collapse list-unstyled <%= 'show' if @current_path.include?('users') %>" id="userSubmenu">
        <li>
            <% active_class = @current_path.last == 'users' ? 'text-light bg-secondary' : '' %>
            <%= link_to t('.view_users'), admin_users_path, class: active_class %>
        </li>
    </ul>
</li>