config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # Language wrapper
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    # "/en" OR "/ar"
    get "/", to: "user/pages#home", as: "home"
    
    # User Routes "/user"
    get "pages", to: "user/pages#home"
    get "pages/home", to: "user/pages#home"

    # Set user session
    get "/set_user", to: "user/pages#set_user", as: "set_user"

    # Add to cart
    # POST "/add_to_cart/:id"
    post "add_to_cart", to: "user/pages#add_to_cart", as: "add_to_cart"
    # Remove from cart
    # POST "/remove_from_cart/:id"
    post "remove_from_cart", to: "user/pages#remove_from_cart", as: "remove_from_cart"
    # Increment quantity
    # POST "/increment_quantity/:id"
    post "increment_quantity", to: "user/pages#increment_quantity", as: "increment_quantity"
    # decrement quantity
    # POST "/decrement_quantity/:id"
    post "decrement_quantity", to: "user/pages#decrement_quantity", as: "decrement_quantity"
    # Checkout (generate bill)
    # POST "/checkout"
    post "checkout", to: "user/pages#checkout", as: "checkout"

    get "generate_invoice",  to: "user/pages#generate_invoice", as: "generate_invoice"


    # Admin Routes "/admin"
    namespace :admin do
      # Market routes 
      # GET "/markets", GET "/markets/:id"
      # PUT "/markets/:id", POST "/markets", DELETE "/markets/:id"
      resources :markets

      # GET "/categories", GET "/categories/:id"
      # PUT "/categories/:id", POST "/categories", DELETE "/categories/:id"
      resources :categories

      # Upload product routes
      # GET "/products/new_upload"
      get "products/new_upload", to: "products#new_upload", as: "new_upload"
      # POST "/products/new_upload"
      post "products/upload_products", to: "products#upload_products", as: "upload_products"
      # GET "/products", GET "/products/:id"
      # PUT "/products/:id", POST "/products", DELETE "/products/:id"
      resources :products

      # Orders Routes
      # GET "/orders"
      get "orders", to: "orders#index", as: "orders"
      # GET "/order/:id"
      get "order/:id", to: "orders#show", as: "order"
      # DELETE "order/:id"
      delete "order/:id", to: "orders#destroy", as: "destroy_order"
      # GET "/invoice/:id"
      get "invoice/:id", to: "orders#view_invoice", as: "invoice"
      # POST "/generate_invoice/:order_id"
      post "invoice/:id", to: "orders#generate_invoice", as: "generate_invoice"

      # Users Routes
      # GET "/users"
      resources :users, only: [:index, :show, :edit, :update]

      # Settings Routes
      # GET "/settings"
      get "settings", to: "settings#index", as: "settings"
      # POST "/change_settings"
      post "change_settings", to: "settings#change_settings", as: "change_settings"
      
      # Admin Landing page "/admin"
      get "/", to: "pages#main"
      get "pages/main"
      # No route match
      # TODO: create a route for undefined routes for admins
    end

    # No routes match
    get "*path", to: "user/pages#no_match", as: "no_match"
  end
  
  # Root "/"
  root "user/pages#home"
  get "*path", to: redirect("/#{I18n.locale}/%{path}")
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                  :bigint           not null, primary key
#  user_id             :bigint
#  order_price         :decimal(10, 2)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  confirmed           :boolean
#  confirmed_by        :integer
#  checkout_at         :datetime
#  confirmed_at        :datetime
#  max_total_price     :decimal(10, 2)
#  min_total_price     :decimal(10, 2)
#  max_market_id       :integer
#  min_market_id       :integer
#  average_total_price :decimal(10, 2)
#

class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  belongs_to :user, optional: true
  belongs_to :admin, foreign_key: :confirmed_by, optional: true

  # before_create :clear_empty_carts
  
  default_scope { includes(:order_products, :products, :user, :admin) }
  scope :proceeded, -> { where.not(user_id: nil) }
  scope :filled_carts, -> { where(user_id: nil).where('EXISTS(SELECT 1 FROM order_products WHERE order_id = orders.id)') }
  scope :empty_carts, -> { where(user_id: nil).where('NOT EXISTS(SELECT 1 FROM order_products WHERE order_id = orders.id)') }
  scope :not_confirmed, -> { where(confirmed: false) }
  scope :confirmed, -> { where(confirmed: true) }


  def self.get_report(interval)
    if interval == 'daily'
      format = 'Mon-dd-YYYY'
    elsif interval == 'monthly'
      format = 'Mon'
    elsif interval == 'YYYY'
      format = '%Y'
    end
    report = {}
    o_kind = Order.select("orders.id,max(order_price) as max_price,min(order_price) as min_price,
    orders.user_id,orders.confirmed_by,to_char(created_at, '#{format}') as comee, avg(order_price) as average_order_price,
    count(orders.id) as purchase")
    .group("to_char(created_at, '#{format}'),orders.id")
    report["count"] = o_kind.collect(&:purchase)
    report["average_order_price"] = o_kind.collect(&:average_order_price)
    report["max_price"] = o_kind.collect(&:max_price)
    report["min_price"] = o_kind.collect(&:min_price)

    report["o_time"] =  o_kind.collect(&:comee)
    report 
  end


  

  private

  def clear_empty_carts
    Order.empty_carts.destroy_all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
    def index
        @orders = Order.proceeded.order('confirmed DESC, created_at DESC')

        if params[:customer_phone] && !params[:customer_phone].empty?
            user = User.where('mobile like ?', "%#{params[:customer_phone]}%").first
            @orders = user.orders if user
        end
        if params[:user_id] && !params[:user_id].empty?
            if User.find_by(id: params[:user_id])
                user = User.find(params[:user_id])
                @orders = user.orders
            else
                flash[:warning] = "No such user with the entered ID"
            end
        end
        @orders = @orders.where(confirmed: true) if params[:confirmation].to_i == 1
        @orders = @orders.where(confirmed: nil) if params[:confirmation].to_i == 2
        # @orders = @orders.joins(:user).where(user: {mobile: params[:customer_phone]}) if params[:customer_phone] && !params[:customer_phone].empty?
        @orders = @orders.page params[:page]
    end
    
    def show
        @order = Order.find(params[:id])
        @order_products = @order.order_products
        @counts = {
            product_count: @order_products.size,
            quantity_count: @order_products.sum { |item| item.quantity }
        }
        @markets = Market.active
    end

    def destroy
        order = Order.find(params[:id])
        order.destroy
        redirect_to admin_orders_path, flash: { notice: 'Order Deleted Successfully' }
    end

    def view_invoice
        @order = Order.find(params[:id])
        @order_products = @order.order_products
        @markets = Market.active
    end

    def generate_invoice
        order = Order.find(params[:id])
        msg = { notice: 'Invoice generated successfully' }
        
        if order.user_id
            order.confirmed = true
            order.confirmed_by = params[:admin]
            order.confirmed_at = DateTime.now
            # raise ''
            order.save
        else
            msg = { alert: 'Cannot generate invoice on unprocessed Cart' }
        end

        redirect_to admin_invoice_path(order), flash: msg
    end

    def record_not_found
        flash[:warning] = "Record Not Found"
        redirect_to :back
    end
    
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_filter.html.erb
<div class="accordion mb-5" id="accordionExample">
    <div class="card">
        <div class="card-header pointer" id="headingOne" data-toggle="collapse" data-target="#filter" aria-expanded="true" aria-controls="filter">
            <h5 class="mb-0">
                <%= t ".filter" %>
            </h5>
        </div>
        <div id="filter" class="collapse <%= 'show' if params[:filtering] %>" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                <%= form_with model: @filter, url_fo: admin_orders_path, local: true, method: :get, id: 'filter-form' do |f| %>
                    <%= f.hidden_field :filtering %>
                    <div class="fomr-group row my-3">
                        <div class="col-md-6 row">
                            <%= f.label t(".user_id"), for: "user_id", class: 'col-md-4' %>
                            <%= f.text_field :user_id, class: 'form-control col-md-8', value: params[:user_id] ? params[:user_id] : '' %>
                        </div>
                    </div>
                    <div class="fomr-group row my-3">
                        <div class="col-md-6 row">
                            <%= f.label t(".customer_phone"), for: "customer_phone", class: 'col-md-4' %>
                            <%= f.text_field :customer_phone, class: 'form-control col-md-8', value: params[:customer_phone] ? params[:customer_phone] : '' %>
                        </div>
                    </div>
                    <div class="fomr-group row my-3">
                        <div class="col-md-6 row">
                            <%= f.label t(".confirmation"), class: 'col-md-4', for: 'confirmation' %>
                            <%= f.select :confirmation, options_for_select([[t(".all"), 0], [t(".is_confirmed"), 1], [t(".not_confirmed"), 2]], params[:confirmation]), {}, {class: 'form-control', :style => 'width: 200px'} %>
                        </div>
                    </div>
                    <div class="form-group mt-5 text-center">
                        <%= f.submit t(".submit"), class: 'btn btn-outline-info' %>
                        <div class="gap-x-sm"></div>
                        <%= link_to t(".clear"), admin_orders_path, class: 'btn btn-outline-danger' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/orders/_order_details.html.erb
<div class="row">
    <div class="col">
        <h5><%= t ".order_products" %></h5>
        <br>
        <table class="table table-hover text-center">
            <thead class="thead-light">
                <th>#</th>
                <th><%= t ".image" %></th>
                <th><%= Product.human_attribute_name("name#{is_ar ? '' : '_en'}") %></th>
                <th><%= t ".quantity" %></th>
            </thead>
            <tbody>
                <% if @order_products.size == 0 %>
                    <tr>
                        <td colspan="4" class="text-danger">
                            <%= t ".no_products" %>
                        </td>
                    </tr>
                <% end %>
                <% @order_products.each_with_index do |item, i| %>
                    <% product = item.product %>
                        <tr>
                            <td>
                                <%= i + 1 %>
                            </td>
                            <td>
                                <%= image_tag product.main_image, class: 'product-image' if product.main_image && !product.main_image.empty? %>
                            </td>
                            <td>
                                <%= link_to product.lang_name, admin_product_path(product) %>
                            </td>
                            <td>
                                <p><%= item.quantity %></p>
                            </td>
                        </tr>
                <% end %>
            </tbody>
            <tfoot class="tfoot-dark">
                <tr>
                    <td>
                        <%= t ".total_products" %>
                    </td>
                    <td>
                        <%= @counts[:product_count] %>
                    </td>
                    <td>
                        <%= t ".total_quantity" %>
                    </td>
                    <td>
                        <%= @counts[:quantity_count] %>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="gap-x-sm"></div>
    <div class="col">
        <h5><%= t ".order_times" %></h5>
        <br>
        <ul class="list-group list-group-flush">
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".id"%>:</strong>
                <div class="gap-x-sm"></div>
                <span class="text-center">
                    <%= @order.id %>
                </span>
            </li>
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".created_at"%>:</strong>
                <div class="gap-x-sm"></div>
                <span class="text-center">
                    <%= format_date @order.created_at %>
                </span>
            </li>
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".ordered_at"%>:</strong>
                <div class="gap-x-sm"></div>
                <span class="text-center">
                    <%= format_date @order.checkout_at if @order.checkout_at %>
                </span>
            </li>
            <li class="list-group-item list-group-item-action d-flex">
                <strong style="min-width: 200px;"><%= t ".confirmed_at"%>:</strong>
                <div class="gap-x-sm"></div>
                <% if @order.confirmed %>
                    <span class="text-center text-success">
                        <%= format_date(@order.created_at) %>
                    </span>
                <% else %>
                    <span class="text-center text-danger">
                        <%= t(".not_confirmed") %>
                    </span>
                <% end %>
            </li>
            <% if @order.admin %>
                <li class="list-group-item list-group-item-action d-flex">
                    <strong style="min-width: 200px;"><%= t ".confirmed_by"%>:</strong>
                    <div class="gap-x-sm"></div>
                    <span class="text-center text-info">
                        <%= @order.admin.email %>
                    </span>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/admin/orders/_prices_details.html.erb
<%
    totals = {}
    total_quantity = 0
%>
<div>
    <table class="table table-hover text-center">
        <thead>
            <th class="bg-light"><%= Product.model_name.human %></th>
            <th><%= t ".quantity" %></th>
            <% @markets.each do |market| %>
                <th>
                    <%= market.lang_name %>
                </th>
            <% end %>
        </thead>
        <tbody>
            <% if @order_products.size == 0 %>
                <tr>
                    <td colspan="4" class="text-danger">
                        <%= t ".no_products" %>
                    </td>
                </tr>
            <% end %>
            <% @order_products.each do |item| %>
                <% product = item.product %>
                <% quantity = item.quantity %>
                <tr>
                    <td class="bg-light" style="max-width: 150px">
                        <%= product.lang_name %>
                    </td>
                    <td>
                        <% total_quantity += quantity %>
                        <%= quantity %>
                    </td>
                    <% product.informations.order_by_market_name.each do |item_price| %>
                        <td>
                            <% price = item_price.price.to_f * quantity %>
                            <% totals[item_price.market_id] = totals[item_price.market_id] ? totals[item_price.market_id] + price : price %>
                            <%= number_to_currency price, locale: @lang %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
        <tfoot class="tfoot-dark">
            <tr>
                <td><%= t ".total" %></td>

                <td><%= totals['quantity'] %></td>
                
                <%
                    min = totals.min_by{ |k,v| v }
                    max = totals.max_by{ |k,v| v }
                %>

                <% @markets.each do |market| %>
                    <% if min && max %>
                        <% if min.last && totals[market.id] == min.last %>
                            <td class="text-success">
                                <%= number_to_currency totals[market.id], locale: @lang %>
                            </td>
                        <% elsif max.last && totals[market.id] == max.last %>
                            <td class="text-danger">
                                <%= number_to_currency totals[market.id], locale: @lang %>
                            </td>
                        <% else %>
                            <td>
                                <%= number_to_currency totals[market.id], locale: @lang %>
                            </td>
                        <% end %>
                    <% end %>
                <% end %>
            </tr>
        </tfoot>
    </table>
    <br><br>
    <div class="row third-width">
        <% text_align = is_ar ? 'right' : 'left' %>
        <div class="col-md-5 text-<%= text_align %>">
            <strong><%= t ".saving_amount" %>:</strong>
        </div>
        <div class="col text-success text-<%= text_align %>">
            <%= number_to_currency((max.last - min.last).round(2), locale: @lang) if min && max %>
        </div>
    </div>
</div>

app/views/admin/orders/_user_details.html.erb
<% user = @order.user %>
<div class="row mb-5 pb-5">
    <ul class="list-group list-group-flush col-md-4">
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".id"%>:</strong>
            <span class="text-center">
                <%= link_to user.id, admin_user_path(user) %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".name"%>:</strong>
            <span class="text-center">
                <%= link_to user.name, admin_user_path(user) %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".phone"%>:</strong>
            <span class="text-center">
                <%= user.mobile %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".email"%>:</strong>
            <span class="text-center">
                <%= user.email != '' ? user.email : t(".no_email") %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".order_count"%>:</strong>
            <span class="text-center">
                <%= user.orders.size %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".joined_at"%>:</strong>
            <span class="text-center">
                <%= format_date user.created_at %>
            </span>
        </li>
        <li class="list-group-item list-group-item-action d-flex">
            <strong style="min-width: 200px;"><%= t ".last_visit"%>:</strong>
            <span class="text-center text-<%= user.last_visit ? "info" : "danger" %>">
                <%= user.last_visit ? format_date(user.last_visit) : t(".unknown") %>
            </span>
        </li>
    </ul>
</div>

app/views/admin/orders/index.html.erb
<h2><%= t ".all_orders" %></h2>
<div class="divider"></div>
<br>
<br>

<%= render partial: 'filter' %>


<table class="table table-hover text-center mb-5 pb-5">
  <thead class="thead-light">
    <tr>
      <th># ID</th>
      <th><%= t ".order_number" %></th>
      <th><%= User.model_name.human %></th>
      <th><%= t ".confirmed" %></th>
      <th><%= t ".ordered_at" %></th>
      <th colspan="3" class="text-info"><%= t ".actions" %></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= "#{order.created_at.year}#{order.id}" %></td>
        <td>
          <% if order.user %>
            <%= order.user.name %><br><%= order.user.mobile %>
          <% end %>
        </td>
        <td>
          <% if order.confirmed %>
            <span class="text-success"><%= t ".is_confirmed" %></span>
            <br>
            <%= format_date order.confirmed_at %>
          <% else %>
            <span class="text-danger"><%= t ".not_confirmed" %></span>
          <% end %>
        </td>
        <td>
          <%= format_date order.created_at %>
        </td>
        <td>
          <%= link_to url_for(admin_order_path(order)), class: 'btn btn-outline-info btn-sm pt-2', title: t(".view") do %>
            <i class="fa fa-eye"></i>
          <% end %>
          <% if !order.confirmed %>
            <%= link_to(url_for(admin_generate_invoice_path(order, admin: current_admin)),
                        class: 'btn btn-outline-success btn-sm pt-2',
                        method: :post,
                        title: t(".generate_invoice")
                ) do
            %>
              <i class="fas fa-file-invoice-dollar fa-lg"></i>
            <% end %>
          <% else %>
            
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="row my-2 mx-auto pagination">
    <%= paginate @orders %>
</div>


<script>
  $(document).ready(function() {
      $('select').select2();
  });
</script>

app/views/admin/orders/show.html.erb
<%= link_to url_for(admin_orders_path), class: 'text-secondary' do %>
  <i class="fa fa-2x fa-arrow-circle-<%= is_ar ? 'right' : 'left' %>"></i>
<% end %>
<br>
<br>
<div class="row align-items-center">
    <h2 class=""><%= t ".title" %></h2>
</div>
<br>

<h4 class="mt-5"><%= t ".order_info" %></h4>
<div class="divider"></div>
<%= render partial: 'order_details' %>
<div class="divider"></div>

<h4 class="mt-5"><%= t ".prices_info" %></h4>
<div class="divider"></div>
<%= render partial: 'prices_details' %>
<div class="divider"></div>
<% if @order.order_products.size == 0 %>
  <div class="text-center">
    <p class="text-secondary"><%= t ".no_products" %></p>
    <%= link_to t(".delete_order"), admin_destroy_order_path(@order), method: :delete, class: "btn btn-outline-danger", data: { confirm: t(".delete_confirmation") } %>
  </div>
<% elsif @order.checkout_at %>
  <% if !@order.confirmed %>
    <div class="text-center">
      <%= link_to t(".generate_invoice"), admin_generate_invoice_path(@order, admin: current_admin), class: 'btn btn-info', method: :post %>
    </div>
  <% else %>
    <div class="text-center">
      <%= link_to t(".view_invoice"), admin_invoice_path(@order), class: 'btn btn-success' %>
    </div>
  <% end %>
  <br><br>
<% end %>

<% if @order.user %>
  <h4 class="mt-5"><%= t ".user_info" %></h4>
  <div class="divider"></div>
  <%= render partial: 'user_details' %>
<% end %>

app/views/admin/orders/view_invoice.html.erb
<%= stylesheet_link_tag "invoice", media: "print" %>

<% align_text = is_ar ? 'right' : 'left' %>

<style>
    body{
    font-family: <%= is_ar ? "Tajawal, sans-serif;" : "Ubuntu, sans-serif;" %>
    }
</style>

<div class="invoice-wrapper text-center">
    <div class="main">
        <div class="header">
            <div class="row">
                <div class="col">
                    <%= image_tag 'user/logo.png' %>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-5 d-flex align-items-end justify-content-center">
                    <ul class="list-unstyled no-padding no-margin full-width">
                        <li class="row">
                            <strong class="col-md-4"><%= t ".customer_name" %>:</strong>
                            <span class="col text-<%= align_text %>"><%= @order.user.name %></span>
                        </li>
                        <li class="row">
                            <strong class="col-md-4"><%= t ".customer_phone" %>:</strong>
                            <span class="col text-<%= align_text %>" dir="ltr"><%= "+966 #{@order.user.mobile}" %></span>
                        </li>
                        <li class="row">
                            <strong class="col-md-4"><%= t ".order_code" %>:</strong>
                            <span class="col text-<%= align_text %>" ><%= "#{@order.created_at.year}#{@order.id}" %></span>
                        </li>
                        <li class="row">
                            <strong class="col-md-4"><%= t ".ordered_at" %>:</strong>
                            <span class="col text-<%= align_text %>"><%= format_date @order.created_at %></span>
                        </li>
                    </ul>
                </div>
                <div class="col"></div>
                <div class="col-md-4 d-flex align-items-start justify-content-center">
                    <ul class="list-unstyled no-padding no-margin full-width">
                        <li class="row">
                            <strong class="col-md-4"><%= t ".generated_at" %>:</strong>
                            <span class="col text<%= align_text %>"><%= format_date @order.confirmed_at %></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="body my-5 py-5">
            <h4 class="text-<%= align_text %>"><%= t ".price_list" %></h4>
            <%= render partial: 'prices_details' %>
            <div class="my-5"></div>
            <div class="panel panel-default">
                <div class="panel-body text-secondary pt-5">
                    <strong><%= t ".note" %></strong>: <%= t ".note_info" %>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <ul dir="ltr" class="list-unstyled d-flex align-items-center justify-content-center">
            <li>
                <%= link_to "tel:#{+966503496466}", class: 'text-info px-3' do %>
                    <i class="fab fa-whatsapp"></i> +966 50 349 6466
                <% end %>
            </li>
            <li>
                <%= link_to "https://twitter.com/Qaren_sa", class: 'text-info px-3' do %>
                    <i class="fab fa-twitter"></i> Qaren_sa
                <% end %>
            </li>
        </ul>
        <p class="text-secondary">&copy; <%= "#{Time.new.year} #{t ".rights"}" %></p>
    </div>
</div>