config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # Language wrapper
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    # "/en" OR "/ar"
    get "/", to: "user/pages#home", as: "home"
    
    # User Routes "/user"
    get "pages", to: "user/pages#home"
    get "pages/home", to: "user/pages#home"

    # Set user session
    get "/set_user", to: "user/pages#set_user", as: "set_user"

    # Add to cart
    # POST "/add_to_cart/:id"
    post "add_to_cart", to: "user/pages#add_to_cart", as: "add_to_cart"
    # Remove from cart
    # POST "/remove_from_cart/:id"
    post "remove_from_cart", to: "user/pages#remove_from_cart", as: "remove_from_cart"
    # Increment quantity
    # POST "/increment_quantity/:id"
    post "increment_quantity", to: "user/pages#increment_quantity", as: "increment_quantity"
    # decrement quantity
    # POST "/decrement_quantity/:id"
    post "decrement_quantity", to: "user/pages#decrement_quantity", as: "decrement_quantity"
    # Checkout (generate bill)
    # POST "/checkout"
    post "checkout", to: "user/pages#checkout", as: "checkout"

    get "generate_invoice",  to: "user/pages#generate_invoice", as: "generate_invoice"


    # Admin Routes "/admin"
    namespace :admin do
      # Market routes 
      # GET "/markets", GET "/markets/:id"
      # PUT "/markets/:id", POST "/markets", DELETE "/markets/:id"
      resources :markets

      # GET "/categories", GET "/categories/:id"
      # PUT "/categories/:id", POST "/categories", DELETE "/categories/:id"
      resources :categories

      # Upload product routes
      # GET "/products/new_upload"
      get "products/new_upload", to: "products#new_upload", as: "new_upload"
      # POST "/products/new_upload"
      post "products/upload_products", to: "products#upload_products", as: "upload_products"
      # GET "/products", GET "/products/:id"
      # PUT "/products/:id", POST "/products", DELETE "/products/:id"
      resources :products

      # Orders Routes
      # GET "/orders"
      get "orders", to: "orders#index", as: "orders"
      # GET "/order/:id"
      get "order/:id", to: "orders#show", as: "order"
      # DELETE "order/:id"
      delete "order/:id", to: "orders#destroy", as: "destroy_order"
      # GET "/invoice/:id"
      get "invoice/:id", to: "orders#view_invoice", as: "invoice"
      # POST "/generate_invoice/:order_id"
      post "invoice/:id", to: "orders#generate_invoice", as: "generate_invoice"

      # Users Routes
      # GET "/users"
      resources :users, only: [:index, :show, :edit, :update]

      # Settings Routes
      # GET "/settings"
      get "settings", to: "settings#index", as: "settings"
      # POST "/change_settings"
      post "change_settings", to: "settings#change_settings", as: "change_settings"
      
      # Admin Landing page "/admin"
      get "/", to: "pages#main"
      get "pages/main"
      # No route match
      # TODO: create a route for undefined routes for admins
    end

    # No routes match
    get "*path", to: "user/pages#no_match", as: "no_match"
  end
  
  # Root "/"
  root "user/pages#home"
  get "*path", to: redirect("/#{I18n.locale}/%{path}")
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :bigint           not null, primary key
#  name          :string
#  name_en       :string
#  description   :text
#  main_image    :string
#  category_id   :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  lowest_price  :decimal(6, 2)
#  highest_price :decimal(6, 2)
#  basket_type   :integer
#

class Product < ApplicationRecord
  has_many :order_products, dependent: :destroy
  has_many :informations, class_name: "ProductInformation", dependent: :destroy
  has_many :markets, through: :product_informations
  has_many :orders, through: :order_products
  belongs_to :category, optional: true
  
  def lang_name
    lang = I18n.locale.to_s
    lang == "ar" ? self['name'] : self["name_#{lang}"]
  end

  def get_price market_id
    item_price =  self.informations.find_by(market_id: market_id)
    item_price ? item_price.price : ''
  end
  def set_price market_id, val
    # Find or create the price for the current product
    product_price = self.informations.find_or_create_by(market_id: market_id)
    product_price.price = val
    product_price.save
  end
  def get_url market_id
    item_url =  self.informations.find_by(market_id: market_id)
    item_url ? item_url.market_url : ''
  end
  def set_url market_id, val
    # Find or create the price for the current product
    product_url = self.informations.find_or_create_by(market_id: market_id)
    product_url.market_url = val
    product_url.save
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  require 'csv'
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = @products.where(category_id: params[:category_id]) if params[:category_id] && !params[:category_id].empty?
    @products = @products.where('name ilike ?', "%#{params[:product_name]}%") if params[:product_name] && !params[:product_name].empty?
    @products = @products.order("name#{or_en}").page params[:page]
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @markets = Market.all.order('active DESC, name')
  end

  # GET /products/new
  def new
    @product = Product.new
    @markets = Market.all.order('active DESC, name')
  end

  # GET /products/1/edit
  def edit
    @markets = Market.all.order('active DESC, name')
  end

  # GET /products/new-upload
  def new_upload
  end

  # POST /products/upload_products
  def upload_products
    file = params[:sheet]
    msg = {}
    begin
      CSV.foreach(file.path, headers: true) do |row|
        # begin
          status = {
            success: true,
            alert: 'notice',
            msg: "Successfully uploaded products"
          }
          # Get product if exists by ID or Name
          if row['id'] && !row['id'].empty?
            product = Product.find_or_create_by(id: row['id'])
          # Or by name if exists
          elsif row['name'] && !row['name'].empty?
            product = Product.find_or_create_by(name: row['name'])
            product.name_en = row['name_en'] ? row['name_en'] : row['name']
          else
            # Or create a new one without name
            product = Product.new
            product.name = 'لم يتم العثور على اسم'
            product.name_en = 'No name found'
            status[:alert] = 'warning'
            status[:msg] += 'لم يتم ايجاد اسم لبعض المنتجات.'
          end
          
          # Set image
          product.main_image = row['img'] if row['img']
          
          lowest = 0
          highest = 0
          # Set prices for each market
          Market.all.each_with_index do |market, i|
            sheet_name = market.sheet_name
            url_column = market.sheet_url_name
            if row[sheet_name]
              price = row[sheet_name].to_f
            else
              price = 0.to_f
              status[:alert] = 'warning'
              status[:msg] += ' لم يتم ايجاد اسعار بعض المنتجات، قد يكون السبب اختلاف التسمية. '
            end
            if row[url_column]
              url = row[url_column]
            else
              url = nil
              status[:alert] = 'warning'
              status[:msg] += ' لم يتم ايجاد اسعار بعض المنتجات، قد يكون السبب اختلاف التسمية. '
            end
            lowest = price if i == 0 || lowest  > price
            highest = price if i == 0 || highest  < price
            product.set_price(market.id, price)
            product.set_url(market.id, url)
          end

          product.lowest_price = lowest
          product.highest_price = highest
          
          # Set Category
          product.category = Category.find_by(name_in_file: row['category']) if row['category']
          
          # Save changes
          product.save

          msg[status[:alert]] = status[:msg]
        # rescue => ex
        #   msg = { alert: ex.message }
        # end
      end
    rescue CSV::MalformedCSVError
      msg['danger'] = "لم يتم اضافة المنتجات لوجود صيغه لا يمكن التعرف عليها" 
    end
  
    redirect_to admin_new_upload_path, flash: msg
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        market_prices = params[:product][:market_price]
        market_prices.each do |market_id, value|
          @product.set_price(market_id, value)
        end
        market_urls = params[:product][:market_url]
        market_urls.each do |market_id, value|
          @product.set_url(market_id, value.empty? ? nil : value)
        end
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: admin_product_path(@product) }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.update(product_params)
    respond_to do |format|
      if @product.update(product_params)
        prices = params[:product][:market_price]
        prices.each do |market_id, price|
          @product.set_price(market_id, price)
        end
        market_urls = params[:product][:market_url]
        market_urls.each do |market_id, value|
          @product.set_url(market_id, value.empty? ? nil : value)
        end
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_product_path(@product) }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def error_uploading msg
      redirect_to admin_new_upload_path, flash: [alert: msg]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :name_en, :description, :main_image, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_filter.html.erb
<div class="accordion mb-5" id="accordionExample">
    <div class="card">
        <div class="card-header pointer" id="headingOne" data-toggle="collapse" data-target="#filter" aria-expanded="true" aria-controls="filter">
            <h5 class="mb-0">
                <%= t ".filter" %>
            </h5>
        </div>
        <div id="filter" class="collapse <%= 'show' if params[:filtering] %>" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                <%= form_with model: @filter, url_fo: admin_orders_path, local: true, method: :get, id: 'filter-form' do |f| %>
                    <%= f.hidden_field :filtering %>
                    <div class="fomr-group row my-3">
                        <div class="col-md-6 row">
                            <%= f.label t(".product_name"), for: "product_name", class: 'col-md-4' %>
                            <%= f.text_field :product_name, class: 'form-control col-md-8', value: params[:product_name] ? params[:product_name] : '' %>
                        </div>
                    </div>
                    <div class="fomr-group row my-3">
                        <div class="col-md-6 row">
                            <%= f.label t(".category"), class: 'col-md-4', for: 'confirmation' %>
                            <%= f.collection_select(
                                    :category_id,
                                    Category.all.order(:id), :id, :lang_name,
                                    { selected: params[:category_id], include_blank: t(".all") },
                                    { style: 'width: 200px' }
                                )
                            %>
                        </div>
                    </div>
                    <div class="form-group mt-5 text-center">
                        <%= f.submit t(".submit"), class: 'btn btn-outline-info' %>
                        <div class="gap-x-sm"></div>
                        <%= link_to t(".clear"), admin_products_path, class: 'btn btn-outline-danger' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>



<script>
    $(document).ready(function() {
        $('select').select2();
    });
</script>

app/views/admin/products/_form.html.erb
<%= form_with(model: product, url: edit ? admin_product_path(product) : admin_products_path, local: true, class: 'two-thirds-width') do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: 'col-md-2 text-center' %>
    <%= form.text_field :name, class: 'form-control col-md-6' %>
  </div>

  <div class="form-group row">
    <%= form.label :name_en, class: 'col-md-2 text-center' %>
    <%= form.text_field :name_en, class: 'form-control col-md-6' %>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: 'col-md-2 text-center' %>
    <%= form.text_area :description, class: 'form-control col-md-6' %>
  </div>

  <div class="form-group row">
    <%= form.label :main_image, class: 'col-md-2 text-center' %>
    <%= form.text_field :main_image, class: 'form-control col-md-6' %>
  </div>

  <div class="form-group row">
    <%= form.label :category_id, class: 'col-md-2 text-center' %>
    <%= collection_select(:product, :category_id, Category.all, :id, is_ar ? :name : "name_#{@lang}".to_sym, {include_blank: "#{Category.all.empty? ? 'Please add category' : 'Please choose'}"}, {:class=>'form-control col-md-6'}) %>
    <%# form.text_field :category_id %>
  </div>

  <%# Market prices %>
  <div class="divider"></div>
  <br>
  <div class="text-center row text-secondary">
    <p class="col-2"><%= t ".prices" %></p>
  </div>
  <br>
  <% @markets.each do |market| %>
    <div class="form-group row">
      <%= form.label market.lang_name, for: "product_#{market.id}", class: 'col-md-2 text-center' %>
      <%= form.number_field "market_price[#{market.id}]", id: market.id, min: 1, value: product.get_price(market.id), class: 'form-control col-md-2', step: :any %>
    </div>
    <div class="form-group row">
      <%= form.label t('.url_for', market: market.lang_name), for: "product_#{market.id}", class: 'col-md-2 text-center' %>
      <%= form.text_field(
        "market_url[#{market.id}]",
        id: "url_#{market.id}",
        min: 1,
        value: product.get_url(market.id),
        placeholder: 'www.example.com/product_url',
        class: 'form-control col-md-6') %>
    </div>
  <% end %>

  <div class="actions form-group text-center">
    <%= form.submit class: 'btn btn-info' %>
  </div>
<% end %>

<script>
  $(document).ready(function() {
      $('select').select2();
  });
</script>

app/views/admin/products/edit.html.erb
<%= link_to url_for(admin_products_path), class: 'text-secondary' do %>
  <i class="fa fa-2x fa-arrow-circle-<%= is_ar ? 'right' : 'left' %>"></i>
<% end %>
<br>
<br>
<div class="row align-items-center">
    <h2 class=""><%= t ".title" %></h2>
    <%= link_to url_for(admin_product_path(@product)), class: 'col text-info' do %>
        <i class="fa fa-eye"></i>
    <% end %>
</div>
<div class="divider"></div>
<%= render 'form', product: @product, edit: true %>

app/views/admin/products/index.html.erb
<h2><%= Product.model_name.human(count: 2) %></h2>
<div class="divider"></div>
<br>
<%= link_to t(".new_product"), new_admin_product_path, class: "btn btn-info" %>
<br>
<br>

<%= render partial: 'filter' %>

<table class="table table-hover text-center mb-5 pb-5">
  <thead class="thead-light">
    <tr>
      <th>ID #</th>
      <th><%= Product.human_attribute_name('main_image') %></th>
      <th style="width: 20%"><%= Product.human_attribute_name('name') %></th>
      <th style="width: 20%"><%= Product.human_attribute_name('name_en') %></th>
      <th><%= Product.human_attribute_name('description') %></th>
      <th><%= Category.model_name.human(count: 1) %></th>
      <% if @show_lowest_price %>
        <th style="color: darkgreen"><%= Product.human_attribute_name('lowest_price') %></th>
        <th style="color: darkred"><%= Product.human_attribute_name('highest_price') %></th>
      <% end %>
      <th colspan="3" class="text-info"><%= t ".actions" %></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= image_tag product.main_image, class: 'product-image' if product.main_image && !product.main_image.empty? %></td>
        <td><%= product.name %></td>
        <td><%= product.name_en %></td>
        <td><%= product.description %></td>
        <td><%= product.category.lang_name if product.category %></td>
        <% if @show_lowest_price %>
          <td class="text-success"><%= product.lowest_price ? number_to_currency(product.lowest_price, locale: @lang) : 'Not Found' %></td>
          <td class="text-danger"><%= product.highest_price ? number_to_currency(product.highest_price, locale: @lang) : 'Not Found' %></td>

        <% end %>
        <td>
          <div class="d-flex flex-column">
            <div class="pt-1">
              <%= link_to url_for(admin_product_path(product)), class: 'btn btn-outline-info btn-sm' do %>
                <em class="fa fa-eye"></em>
              <% end %>
            </div>
            <div class="pt-1">
              <%= link_to url_for(edit_admin_product_path(product)), class: 'btn btn-outline-secondary btn-sm' do %>
                <em class="fa fa-edit"></em>
              <% end %>
            </div>
            <div class="pt-1">
              <%= link_to url_for(admin_product_path(product)), class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } do %>
                <em class="fa fa-trash-alt"></em>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="row my-2 mx-auto pagination">
    <%= paginate @products %>
</div>

<br>

app/views/admin/products/new.html.erb
<%= link_to url_for(admin_products_path), class: 'text-secondary' do %>
    <i class="fa fa-2x fa-arrow-circle-<%= is_ar ? 'right' : 'left' %>"></i>
<% end %>
<br>
<br>
<h2><%= t ".title" %></h2>
<div class="divider"></div>
<%= render 'form', product: @product, edit: false %>

app/views/admin/products/new_upload.html.erb
<%= link_to url_for(admin_products_path), class: 'text-secondary' do %>
    <i class="fa fa-2x fa-arrow-circle-<%= is_ar ? 'right' : 'left' %>"></i>
<% end %>
<br>
<br>
<h2><%= t ".title" %></h2>
<div class="divider"></div>

<%= form_with(url: admin_upload_products_path, local: true, class: 'two-thirds-width row', multipart: true) do |form| %>
    <div class="form-group col-md-8">
        <input type="file" class="form-control" id="uploadSheet" name="sheet" required>
    </div>

    <div class="actions form-group text-center col-md-4">
        <%= form.submit t(".upload"), class: 'btn btn-info' %>
    </div>
<% end %>

app/views/admin/products/show.html.erb
<%= link_to url_for(admin_products_path), class: 'text-secondary' do %>
  <i class="fa fa-2x fa-arrow-circle-<%= is_ar ? 'right' : 'left' %>"></i>
<% end %>
<br>
<br>
<div class="row align-items-center">
    <h2 class=""><%= t ".title" %></h2>
    <%= link_to url_for(edit_admin_product_path(@product)), class: 'col text-secondary' do %>
        <i class="fa fa-edit"></i>
    <% end %>
</div>
<div class="divider"></div>

<%= image_tag @product.main_image, class: 'product-image' if @product.main_image && !@product.main_image.empty? %>
<br>
<br>

<p>
  <strong><%= t ".id" %>:</strong>
  <%= @product.id %>
</p>
<p>
  <strong><%= Product.human_attribute_name("name") %>:</strong>
  <%= @product.name %>
</p>

<p>
  <strong><%= Product.human_attribute_name("name_en") %>:</strong>
  <%= @product.name_en %>
</p>

<p>
  <strong><%= Product.human_attribute_name("description") %>:</strong>
  <%= @product.description %>
</p>

<p>
  <strong><%= Category.model_name.human %>:</strong>
  <%= @product.category.lang_name if @product.category %>
</p>
<div class="divider"></div>
<h4 class="mt-5"><%= t ".prices" %></h4>
<table class="table table-hover table-bordered text-center col-md-10 mx-auto">
  <thead>
    <% @product.informations.order_by_market_name.each do |item_price| %>
      <th>
        <%= link_to admin_market_path(item_price.market.id), class: "underline #{item_price.market.active ? 'text-dark' : 'text-secondary line-through'}" do %>
          <i class="far fa-share-square"></i>
          <%= item_price.market.lang_name %>
        <% end %>
      </th>
    <% end %>
  </thead>
  <tbody>
    <% @product.informations.order_by_market_name.each_with_index do |item_price, i| %>
      <td>
        <% if item_price.market_url %>
          <%= link_to "#{item_price.market_url if item_price.market_url}", target: "_blank" do %>
            <%= item_price.price ? number_to_currency(item_price.price, locale: @lang) : t(".not_set") %>
          <% end %>
        <% else %>
            <%= item_price.price ? number_to_currency(item_price.price, locale: @lang) : t(".not_set") %>
        <% end %>
      </td>
    <% end %>
  </tbody>
</table>